2022-05-27 08:18:54.728 [cluster-ClusterId{value='628eed160ec4603fc68b51e9', description='null'}-10.248.50.224:27017] INFO  org.mongodb.driver.cluster:  Exception in monitor thread while connecting to server 10.248.50.224:27017
com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:701)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:579)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:415)
	at com.mongodb.internal.connection.InternalStreamConnection.receive(InternalStreamConnection.java:374)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:216)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:109)
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:718)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:576)
	... 5 common frames omitted
2022-05-27 17:36:12.076 [cluster-ClusterId{value='628eed160ec4603fc68b51e9', description='null'}-10.248.50.224:27017] INFO  org.mongodb.driver.cluster:  Exception in monitor thread while connecting to server 10.248.50.224:27017
com.mongodb.MongoSocketReadException: Exception receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:707)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:579)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:415)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342)
	at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:96)
	at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:44)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:131)
	at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:73)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:182)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:109)
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:718)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:576)
	... 10 common frames omitted
2022-05-27 17:36:12.181 [lettuce-eventExecutorLoop-1-1] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:36:22.212 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:36:32.086 [cluster-ClusterId{value='628eed160ec4603fc68b51e9', description='null'}-10.248.50.224:27017] INFO  org.mongodb.driver.cluster:  Exception in monitor thread while connecting to server 10.248.50.224:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:180)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:152)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:107)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
	... 4 common frames omitted
2022-05-27 17:36:32.223 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:36:32.224 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:36:42.243 [lettuce-nioEventLoop-6-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:36:42.265 [lettuce-eventExecutorLoop-1-2] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:36:52.277 [lettuce-nioEventLoop-6-6] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:37:02.290 [lettuce-nioEventLoop-6-7] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:37:02.291 [lettuce-nioEventLoop-6-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:37:12.303 [lettuce-nioEventLoop-6-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:37:12.368 [lettuce-eventExecutorLoop-1-4] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:37:22.374 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:37:32.377 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:37:32.378 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:37:42.384 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:37:42.467 [lettuce-eventExecutorLoop-1-8] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:37:52.475 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:38:02.479 [lettuce-nioEventLoop-6-5] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:38:02.480 [lettuce-nioEventLoop-6-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:38:12.484 [lettuce-nioEventLoop-6-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:38:12.560 [lettuce-eventExecutorLoop-1-4] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:38:22.565 [lettuce-nioEventLoop-6-7] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:38:32.575 [lettuce-nioEventLoop-6-8] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:38:32.576 [lettuce-nioEventLoop-6-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:38:42.581 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:38:42.665 [lettuce-eventExecutorLoop-1-8] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:38:52.674 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:39:02.692 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:39:02.693 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:39:12.700 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:39:12.865 [lettuce-eventExecutorLoop-1-4] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:39:22.872 [lettuce-nioEventLoop-6-5] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:39:32.876 [lettuce-nioEventLoop-6-6] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:39:32.877 [lettuce-nioEventLoop-6-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:39:42.881 [lettuce-nioEventLoop-6-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: connection timed out: /10.248.50.224:12002
2022-05-27 17:39:43.064 [lettuce-eventExecutorLoop-1-8] INFO  io.lettuce.core.protocol.ConnectionWatchdog:  Reconnecting, last destination was /10.248.50.224:12002
2022-05-27 17:39:53.071 [lettuce-nioEventLoop-6-8] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.223:13001: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.223:13001
2022-05-27 17:40:03.078 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.RedisClient:  Cannot connect Redis Sentinel at redis://10.248.50.224:13002: java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.248.50.224:13002
2022-05-27 17:40:03.079 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot retrieve current address from socketAddressSupplier: io.lettuce.core.RedisConnectionException: Cannot connect to a Redis Sentinel: [redis://10.248.50.223:13001, redis://10.248.50.224:13002], reusing cached address /10.248.50.224:12002
2022-05-27 17:40:04.950 [SpringApplicationShutdownHook] WARN  io.lettuce.core.protocol.ConnectionWatchdog:  Cannot reconnect to [/10.248.50.224:12002]: java.util.concurrent.CancellationException
